package com.smarthospital.core.export;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.*;
import com.smarthospital.modules.analytics.dto.*;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class PdfExportUtil {

    // ── Brand colours ──────────────────────────────────────────────────────
    private static final Color BLUE     = Color.decode("#1677ff");
    private static final Color GREEN    = Color.decode("#52c41a");
    private static final Color ORANGE   = Color.decode("#fa8c16");
    private static final Color PURPLE   = Color.decode("#722ed1");
    private static final Color CYAN     = Color.decode("#13c2c2");
    private static final Color RED      = Color.decode("#ff4d4f");
    private static final Color LIGHT_BG = Color.decode("#f5f7fa");
    private static final Color ALT_BG   = Color.decode("#fafafa");
    private static final Color BORDER   = Color.decode("#e8e8e8");
    private static final Color DARK     = Color.decode("#262626");
    private static final Color GRAY     = Color.decode("#8c8c8c");

    private PdfExportUtil() {}

    // ── Fonts ──────────────────────────────────────────────────────────────
    private static Font titleFont()    { return FontFactory.getFont(FontFactory.HELVETICA_BOLD,  16, BLUE); }
    private static Font sectionFont()  { return FontFactory.getFont(FontFactory.HELVETICA_BOLD,  11, BLUE); }
    private static Font metaFont()     { return FontFactory.getFont(FontFactory.HELVETICA,         9, GRAY); }
    private static Font tblHeaderFont(){ return FontFactory.getFont(FontFactory.HELVETICA_BOLD,   9, Color.WHITE); }
    private static Font labelFont()    { return FontFactory.getFont(FontFactory.HELVETICA,         9, DARK); }
    private static Font boldFont()     { return FontFactory.getFont(FontFactory.HELVETICA_BOLD,   9, DARK); }
    private static Font bigNumFont()   { return FontFactory.getFont(FontFactory.HELVETICA_BOLD,  17, DARK); }
    private static Font kpiLabelFont() { return FontFactory.getFont(FontFactory.HELVETICA,         8, GRAY); }
    private static Font footerFont()   { return FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, GRAY); }

    // ── Number helpers ─────────────────────────────────────────────────────
    private static String inr(BigDecimal v) {
        if (v == null) return "₹0";
        return "₹" + String.format("%,.0f", v.doubleValue());
    }
    private static String inrD(double v) {
        return "₹" + String.format("%,.0f", v);
    }
    private static String num(long v)   { return String.format("%,d", v); }
    private static String pct(double v) { return String.format("%.1f%%", v); }

    // ── Page structure helpers ─────────────────────────────────────────────
    private static void addPageHeader(Document doc, String reportTitle,
                                      String dateRange, String generatedBy) throws DocumentException {
        Paragraph t = new Paragraph("SmartHospital — " + reportTitle, titleFont());
        t.setAlignment(Element.ALIGN_CENTER);
        doc.add(t);

        Paragraph m = new Paragraph(
            "Period: " + dateRange + "   |   " +
            "Generated by: " + generatedBy + "   |   " +
            LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm")),
            metaFont());
        m.setAlignment(Element.ALIGN_CENTER);
        m.setSpacingAfter(14);
        doc.add(m);
    }

    private static void addSectionTitle(Document doc, String text) throws DocumentException {
        Paragraph p = new Paragraph(text, sectionFont());
        p.setSpacingBefore(12);
        p.setSpacingAfter(4);
        doc.add(p);

        PdfPTable line = new PdfPTable(1);
        line.setWidthPercentage(100);
        PdfPCell c = new PdfPCell(new Phrase(""));
        c.setBorderWidthTop(0); c.setBorderWidthLeft(0); c.setBorderWidthRight(0);
        c.setBorderWidthBottom(1.2f); c.setBorderColorBottom(BLUE);
        c.setPadding(0); c.setMinimumHeight(1);
        line.addCell(c);
        doc.add(line);
    }

    private static void addFooter(Document doc) throws DocumentException {
        Paragraph f = new Paragraph("© SmartHospital Management System", footerFont());
        f.setAlignment(Element.ALIGN_CENTER);
        f.setSpacingBefore(20);
        doc.add(f);
    }

    // ── KPI grid (3 per row) ───────────────────────────────────────────────
    private record Kpi(String label, String value, String sub) {}

    private static void addKpiGrid(Document doc, List<Kpi> kpis) throws DocumentException {
        int cols = 3;
        PdfPTable grid = new PdfPTable(cols);
        grid.setWidthPercentage(100);
        grid.setSpacingBefore(6);
        grid.setSpacingAfter(8);

        for (Kpi k : kpis) {
            PdfPCell card = new PdfPCell();
            card.setBorder(Rectangle.BOX);
            card.setBorderColor(BORDER);
            card.setBorderWidth(0.5f);
            card.setPaddingLeft(10); card.setPaddingRight(10);
            card.setPaddingTop(8);   card.setPaddingBottom(8);

            Paragraph lbl = new Paragraph(k.label, kpiLabelFont());
            lbl.setSpacingAfter(4);
            Paragraph val = new Paragraph(k.value, bigNumFont());
            val.setSpacingAfter(3);
            Paragraph sub = new Paragraph(k.sub != null ? k.sub : "", kpiLabelFont());

            card.addElement(lbl);
            card.addElement(val);
            card.addElement(sub);
            grid.addCell(card);
        }
        int rem = kpis.size() % cols;
        if (rem != 0) {
            for (int i = 0; i < cols - rem; i++) {
                PdfPCell e = new PdfPCell(new Phrase(""));
                e.setBorder(0);
                grid.addCell(e);
            }
        }
        doc.add(grid);
    }

    // ── Horizontal bar chart ───────────────────────────────────────────────
    private static void addBarChart(Document doc, List<NameValuePoint> data,
                                    Color barColor) throws DocumentException {
        if (data == null || data.isEmpty()) return;
        double maxVal = data.stream().mapToDouble(NameValuePoint::value).max().orElse(1);

        PdfPTable t = new PdfPTable(new float[]{3f, 5f, 1.8f});
        t.setWidthPercentage(100);
        t.setSpacingBefore(4);
        t.setSpacingAfter(6);

        for (int i = 0; i < data.size(); i++) {
            NameValuePoint item = data.get(i);
            Color rowBg = i % 2 == 0 ? Color.WHITE : ALT_BG;
            float pct = (float) Math.max(0.02, item.value() / maxVal);

            // Name
            PdfPCell nameCell = new PdfPCell(new Phrase(item.name(), labelFont()));
            nameCell.setBackgroundColor(rowBg);
            nameCell.setBorderColor(BORDER);
            nameCell.setPadding(6);
            t.addCell(nameCell);

            // Bar (filled + empty nested table)
            PdfPTable bar = new PdfPTable(new float[]{pct, Math.max(0.001f, 1f - pct)});
            bar.setWidthPercentage(100);

            PdfPCell filled = new PdfPCell(new Phrase("  "));
            filled.setBackgroundColor(barColor);
            filled.setBorder(0);
            filled.setMinimumHeight(12);
            bar.addCell(filled);

            PdfPCell empty = new PdfPCell(new Phrase(""));
            empty.setBackgroundColor(rowBg);
            empty.setBorder(0);
            bar.addCell(empty);

            PdfPCell barCell = new PdfPCell(bar);
            barCell.setBackgroundColor(rowBg);
            barCell.setBorderColor(BORDER);
            barCell.setPaddingTop(7); barCell.setPaddingBottom(7);
            barCell.setPaddingLeft(4); barCell.setPaddingRight(4);
            t.addCell(barCell);

            // Value
            PdfPCell valCell = new PdfPCell(new Phrase(inrD(item.value()), boldFont()));
            valCell.setBackgroundColor(rowBg);
            valCell.setBorderColor(BORDER);
            valCell.setPadding(6);
            valCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            t.addCell(valCell);
        }
        doc.add(t);
    }

    // Same bar chart but values are plain counts (no ₹ prefix)
    private static void addCountBarChart(Document doc, List<NameValuePoint> data,
                                         Color barColor) throws DocumentException {
        if (data == null || data.isEmpty()) return;
        double maxVal = data.stream().mapToDouble(NameValuePoint::value).max().orElse(1);

        PdfPTable t = new PdfPTable(new float[]{3f, 5f, 1.5f});
        t.setWidthPercentage(100);
        t.setSpacingBefore(4);
        t.setSpacingAfter(6);

        for (int i = 0; i < data.size(); i++) {
            NameValuePoint item = data.get(i);
            Color rowBg = i % 2 == 0 ? Color.WHITE : ALT_BG;
            float p = (float) Math.max(0.02, item.value() / maxVal);

            PdfPCell nameCell = new PdfPCell(new Phrase(item.name(), labelFont()));
            nameCell.setBackgroundColor(rowBg); nameCell.setBorderColor(BORDER); nameCell.setPadding(6);
            t.addCell(nameCell);

            PdfPTable bar = new PdfPTable(new float[]{p, Math.max(0.001f, 1f - p)});
            bar.setWidthPercentage(100);
            PdfPCell filled = new PdfPCell(new Phrase("  "));
            filled.setBackgroundColor(barColor); filled.setBorder(0); filled.setMinimumHeight(12);
            bar.addCell(filled);
            PdfPCell empty2 = new PdfPCell(new Phrase(""));
            empty2.setBackgroundColor(rowBg); empty2.setBorder(0);
            bar.addCell(empty2);
            PdfPCell barCell = new PdfPCell(bar);
            barCell.setBackgroundColor(rowBg); barCell.setBorderColor(BORDER);
            barCell.setPaddingTop(7); barCell.setPaddingBottom(7);
            barCell.setPaddingLeft(4); barCell.setPaddingRight(4);
            t.addCell(barCell);

            PdfPCell valCell = new PdfPCell(new Phrase(String.format("%,.0f", item.value()), boldFont()));
            valCell.setBackgroundColor(rowBg); valCell.setBorderColor(BORDER);
            valCell.setPadding(6); valCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            t.addCell(valCell);
        }
        doc.add(t);
    }

    // ── Trend table (compact 5-column grid) ───────────────────────────────
    private static void addTrendGrid(Document doc, List<TrendPoint> trend, boolean isCurrency) throws DocumentException {
        if (trend == null || trend.isEmpty()) return;
        int cols = 5;
        float[] widths = new float[cols * 2];
        for (int i = 0; i < widths.length; i++) widths[i] = i % 2 == 0 ? 1.6f : 2.2f;

        PdfPTable t = new PdfPTable(widths);
        t.setWidthPercentage(100);
        t.setSpacingBefore(4);
        t.setSpacingAfter(6);

        int count = 0;
        for (TrendPoint pt : trend) {
            PdfPCell lbl = new PdfPCell(new Phrase(pt.label(), kpiLabelFont()));
            lbl.setBackgroundColor(Color.decode("#e6f4ff"));
            lbl.setBorderColor(BORDER); lbl.setPadding(4);
            t.addCell(lbl);

            String valStr = isCurrency ? inrD(pt.value()) : String.format("%,.0f", pt.value());
            PdfPCell val = new PdfPCell(new Phrase(valStr, boldFont()));
            val.setBackgroundColor(count % cols == 0 ? Color.WHITE : ALT_BG);
            val.setBorderColor(BORDER); val.setPadding(4);
            val.setHorizontalAlignment(Element.ALIGN_RIGHT);
            t.addCell(val);
            count++;
        }
        // Pad last row
        int rem = trend.size() % cols;
        if (rem != 0) {
            for (int i = 0; i < (cols - rem) * 2; i++) {
                PdfPCell e = new PdfPCell(new Phrase(""));
                e.setBorder(0);
                t.addCell(e);
            }
        }
        doc.add(t);
    }

    // ── Generic table ──────────────────────────────────────────────────────
    private static void addTable(Document doc, String[] headers,
                                 List<List<String>> rows) throws DocumentException {
        float[] widths = new float[headers.length];
        for (int i = 0; i < widths.length; i++) widths[i] = 1f;

        PdfPTable t = new PdfPTable(widths);
        t.setWidthPercentage(100);
        t.setSpacingBefore(4);
        t.setSpacingAfter(6);

        for (String h : headers) {
            PdfPCell c = new PdfPCell(new Phrase(h, tblHeaderFont()));
            c.setBackgroundColor(BLUE); c.setPadding(6);
            t.addCell(c);
        }
        boolean alt = false;
        for (List<String> row : rows) {
            Color bg = alt ? LIGHT_BG : Color.WHITE;
            for (String v : row) {
                PdfPCell c = new PdfPCell(new Phrase(v != null ? v : "", labelFont()));
                c.setBackgroundColor(bg); c.setBorderColor(BORDER); c.setPadding(5);
                t.addCell(c);
            }
            alt = !alt;
        }
        doc.add(t);
    }

    // ══════════════════════════════════════════════════════════════════════
    // SECTION BUILDERS
    // ══════════════════════════════════════════════════════════════════════

    public static byte[] buildExecutive(ExecutiveDashboardResponse d,
                                        String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Executive Dashboard", dateRange, generatedBy);

            addSectionTitle(doc, "Key Performance Indicators");
            addKpiGrid(doc, List.of(
                new Kpi("Today's Revenue",        inr(d.todayRevenue()),       "vs yesterday"),
                new Kpi("Month Revenue",          inr(d.monthRevenue()),       "vs last month"),
                new Kpi("Total Patients",         num(d.totalPatients()),      "all time"),
                new Kpi("Today's Appointments",   num(d.todayAppointments()),  "vs yesterday"),
                new Kpi("Pending Payments",       inr(d.pendingPayments()),    "outstanding"),
                new Kpi("Doctors Available",      num(d.doctorsAvailableToday()), "today"),
                new Kpi("Current Admissions",     num(d.currentAdmissions()), "IPD active"),
                new Kpi("Lab Tests Today",        num(d.labTestsToday()),      "pathology"),
                new Kpi("Medicine Sales",         inr(d.medicineSalesToday()), "today"),
                new Kpi("Inventory Alerts",       num(d.inventoryAlerts()),   "items low/out")
            ));

            addSectionTitle(doc, "Revenue by Source");
            addBarChart(doc, d.revenueBySource(), BLUE);

            addSectionTitle(doc, "Top Doctors by Revenue");
            addBarChart(doc, d.topDoctors(), GREEN);

            addSectionTitle(doc, "Revenue by Department");
            addBarChart(doc, d.departmentRevenue(), ORANGE);

            addSectionTitle(doc, "Daily Revenue Trend (Last 30 Days)");
            addTrendGrid(doc, d.revenueTrend(), true);

            addSectionTitle(doc, "Patient Registration Growth (Monthly)");
            addTrendGrid(doc, d.patientGrowth(), false);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Executive PDF", e);
        }
    }

    public static byte[] buildFinance(FinanceAnalyticsResponse d,
                                      String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Financial Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Financial Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Total Revenue",          inr(d.totalRevenue()),             dateRange),
                new Kpi("Total Expenses",         inr(d.totalExpenses()),            dateRange),
                new Kpi("Net Profit",             inr(d.netProfit()),                dateRange),
                new Kpi("Collection Efficiency",  pct(d.collectionEfficiencyPct()),  dateRange)
            ));

            addSectionTitle(doc, "Revenue by Source");
            addBarChart(doc, d.revenueBySource(), BLUE);

            addSectionTitle(doc, "Revenue by Doctor (Top 10)");
            addBarChart(doc, d.revenueByDoctor(), GREEN);

            addSectionTitle(doc, "Monthly Revenue Comparison");
            addBarChart(doc, d.monthlyComparison(), CYAN);

            addSectionTitle(doc, "Daily Revenue Trend");
            addTrendGrid(doc, d.dailyRevenue(), true);

            addSectionTitle(doc, "Daily Expense Trend");
            addTrendGrid(doc, d.expenseTrend(), true);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Finance PDF", e);
        }
    }

    public static byte[] buildPatients(PatientAnalyticsResponse d,
                                       String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Patient Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Patient Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Total Patients",    num(d.totalPatients()),             "all time"),
                new Kpi("New This Period",   num(d.newPatientsThisPeriod()),     dateRange),
                new Kpi("Returning",         num(d.returningPatients()),         dateRange),
                new Kpi("Retention Rate",    pct(d.retentionRatePct()),          dateRange)
            ));

            addSectionTitle(doc, "Gender Distribution");
            addCountBarChart(doc, d.genderDistribution(), BLUE);

            addSectionTitle(doc, "Age Distribution");
            addCountBarChart(doc, d.ageDistribution(), PURPLE);

            addSectionTitle(doc, "Blood Group Distribution");
            addCountBarChart(doc, d.bloodGroupDistribution(), CYAN);

            addSectionTitle(doc, "Registration Trend (Monthly)");
            addTrendGrid(doc, d.registrationTrend(), false);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Patients PDF", e);
        }
    }

    public static byte[] buildDoctors(DoctorAnalyticsResponse d,
                                      String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Doctor Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Doctor Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Total Doctors",  num(d.totalDoctors()),  "registered"),
                new Kpi("Active Doctors", num(d.activeDoctors()), "on duty")
            ));

            addSectionTitle(doc, "Doctor Leaderboard");
            addTable(doc,
                new String[]{"#", "Doctor", "Specialization", "Appointments", "Revenue (₹)", "Utilization"},
                d.leaderboard().stream().limit(10).map((e) -> {
                    int rank = d.leaderboard().indexOf(e) + 1;
                    return List.of(
                        String.valueOf(rank),
                        e.doctorName(),
                        e.specialization(),
                        num(e.appointmentsCompleted()),
                        inr(e.revenueGenerated()),
                        pct(e.utilizationPct())
                    );
                }).toList()
            );

            addSectionTitle(doc, "Revenue by Doctor (Top 10)");
            addBarChart(doc, d.revenueByDoctor(), GREEN);

            addSectionTitle(doc, "Appointments by Doctor (Top 10)");
            addCountBarChart(doc, d.appointmentsByDoctor(), BLUE);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Doctors PDF", e);
        }
    }

    public static byte[] buildAppointments(AppointmentAnalyticsResponse d,
                                           String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Appointment Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Appointment Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Total",       num(d.totalAppointments()), dateRange),
                new Kpi("Completed",   num(d.completed()),         dateRange),
                new Kpi("Cancelled",   num(d.cancelled()),         dateRange),
                new Kpi("No Show",     num(d.noShow()),            dateRange),
                new Kpi("Rescheduled", num(d.rescheduled()),       dateRange)
            ));

            addSectionTitle(doc, "Status Distribution");
            addCountBarChart(doc, d.statusDistribution(), BLUE);

            addSectionTitle(doc, "Appointments by Doctor (Top 10)");
            addCountBarChart(doc, d.byDoctor(), GREEN);

            addSectionTitle(doc, "Appointments by Department (Top 10)");
            addCountBarChart(doc, d.byDepartment(), ORANGE);

            addSectionTitle(doc, "Daily Appointment Trend");
            addTrendGrid(doc, d.dailyTrend(), false);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Appointments PDF", e);
        }
    }

    public static byte[] buildPharmacy(PharmacyAnalyticsResponse d,
                                       String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Pharmacy Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Pharmacy Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Total Revenue",    inr(d.totalMedicineRevenue()), dateRange),
                new Kpi("Bills Issued",     num(d.totalBillsIssued()),     dateRange),
                new Kpi("Low Stock Alerts", num(d.lowStockAlerts()),       "items"),
                new Kpi("Expiry Alerts",    num(d.expiryAlerts()),         "items")
            ));

            addSectionTitle(doc, "Top Medicines by Revenue");
            addBarChart(doc, d.topMedicinesByRevenue(), BLUE);

            addSectionTitle(doc, "Revenue by Category");
            addBarChart(doc, d.revenueByCategory(), GREEN);

            addSectionTitle(doc, "Stock Health Distribution");
            addCountBarChart(doc, d.stockHealthDistribution(), CYAN);

            addSectionTitle(doc, "Daily Revenue Trend");
            addTrendGrid(doc, d.revenueTrend(), true);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Pharmacy PDF", e);
        }
    }

    public static byte[] buildLaboratory(LaboratoryAnalyticsResponse d,
                                         String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Laboratory Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Laboratory Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Tests Performed",  num(d.totalTestsPerformed()), dateRange),
                new Kpi("Total Revenue",    inr(d.totalRevenue()),        dateRange),
                new Kpi("Pending Reports",  num(d.pendingReports()),      "awaiting")
            ));

            addSectionTitle(doc, "Top Tests by Volume");
            addCountBarChart(doc, d.topTests(), BLUE);

            addSectionTitle(doc, "Tests by Status");
            addCountBarChart(doc, d.statusDistribution(), GREEN);

            addSectionTitle(doc, "Referrals by Source");
            addCountBarChart(doc, d.byDepartmentReferral(), PURPLE);

            addSectionTitle(doc, "Daily Tests Trend");
            addTrendGrid(doc, d.dailyTestsTrend(), false);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Laboratory PDF", e);
        }
    }

    public static byte[] buildInventory(InventoryAnalyticsResponse d,
                                        String dateRange, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();
            addPageHeader(doc, "Inventory Analytics", dateRange, generatedBy);

            addSectionTitle(doc, "Inventory Summary");
            addKpiGrid(doc, List.of(
                new Kpi("Total Stock Value", inr(d.totalStockValue()),    "current"),
                new Kpi("Total Items",       num(d.totalItems()),         "SKUs"),
                new Kpi("Low Stock",         num(d.lowStockItems()),      "below reorder"),
                new Kpi("Out of Stock",      num(d.outOfStockItems()),    "zero quantity")
            ));

            addSectionTitle(doc, "Stock by Category");
            addBarChart(doc, d.stockByCategory(), BLUE);

            addSectionTitle(doc, "Fast Moving Items");
            addCountBarChart(doc, d.fastMovingItems(), GREEN);

            addSectionTitle(doc, "Slow Moving Items");
            addCountBarChart(doc, d.slowMovingItems(), ORANGE);

            if (d.lowStockList() != null && !d.lowStockList().isEmpty()) {
                addSectionTitle(doc, "Low Stock Alert List");
                addTable(doc,
                    new String[]{"Item", "Category", "Current Stock", "Reorder Level"},
                    d.lowStockList().stream().map(e -> List.of(
                        e.itemName(), e.category(),
                        String.valueOf(e.currentStock()),
                        String.valueOf(e.reorderLevel())
                    )).toList()
                );
            }

            addSectionTitle(doc, "Stock Value Trend");
            addTrendGrid(doc, d.stockValueTrend(), true);

            addFooter(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Inventory PDF", e);
        }
    }

    // ── Generic fallback (used by Excel path and any unmatched section) ────
    public static byte[] build(String title, List<String> headers,
                               List<List<Object>> rows, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4.rotate(), 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();

            Paragraph t = new Paragraph("SmartHospital — " + title, titleFont());
            t.setAlignment(Element.ALIGN_CENTER);
            doc.add(t);

            Paragraph m = new Paragraph(
                "Generated by: " + generatedBy + "   |   " +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm")),
                metaFont());
            m.setAlignment(Element.ALIGN_CENTER);
            m.setSpacingAfter(12);
            doc.add(m);

            PdfPTable table = new PdfPTable(headers.size());
            table.setWidthPercentage(100);
            for (String h : headers) {
                PdfPCell c = new PdfPCell(new Phrase(h, tblHeaderFont()));
                c.setBackgroundColor(BLUE); c.setPadding(6);
                table.addCell(c);
            }
            boolean alt = false;
            for (List<Object> row : rows) {
                Color bg = alt ? LIGHT_BG : Color.WHITE;
                for (Object v : row) {
                    PdfPCell c = new PdfPCell(new Phrase(v != null ? v.toString() : "", labelFont()));
                    c.setBackgroundColor(bg); c.setBorderColor(BORDER); c.setPadding(5);
                    table.addCell(c);
                }
                alt = !alt;
            }
            doc.add(table);

            Paragraph f = new Paragraph("© SmartHospital Management System", footerFont());
            f.setAlignment(Element.ALIGN_CENTER);
            f.setSpacingBefore(20);
            doc.add(f);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF export", e);
        }
    }
}
